---
title: "Notes to reviewers"
author: "Don Boyd"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output:
  html_notebook: 
    df_print: paged
    fig_height: 6
    fig_width: 8
    toc: yes
    toc_float: yes
    number_sections: yes
---

# Overview

1.  CAUTIONS

2.  Set your system up

3.  Set the RStudio `Pew_Revenue_Volatility` project up

4.  Check the setup

5.  Data preparation - step through each of the following programs, in the `r` folder, line by line

6.  Run `Pew_Tax_Revenue_Volatility.rmd` chunk by chunk.

# CAUTIONS

1.  Downloading data (or not)

-   I have included in this project all of the data needed for the report. If you use the included data you should be able to match exactly the figures and tables in the report.

-   However, I also provide tools that created the included data files. These tools consist of (1) packages I created that get and parse data from the internet, and (2) code that downloads files from the Internet. (I have commented-out the download code to reduce the chance of running it accidentally.)

-   Because some of the data are from federal agencies that periodically revise their data, if you use these tools to create your own versions of the data files I include in the project, you may end up using data that have been revised and are very slightly different from my included.

2.  Downloading data (or not)

-   You will see some files not needed in the project, usually in folders named "archive"

-   You can ignore these. They are things I didn't want to delete.

# System setup

-   make sure that you can find in the share drive the project directory `Pew_Revenue_Volatility`

-   make sure you have:

    -   R version 4.1.2 or later installed

    -   a recent version of RStudio installed

    -   if any troubles, please email [me](mailto:donboyd5@gmail.com)

-   copy the entire project directory `Pew_Revenue_Volatility` from the share drive to your machine

# Optional step: FRED api key

-   I created `constants_system.r` to isolate all system-specific information in one place, but I have since streamlined the project so that everything is in the project directory (or subfolder) so you should not have to worry about this

-   if you don't plan to download unemployment rate data from FRED, you do not need to do the step in the next bullet (or you can decide later, and at that point take the action in the next step)

-   IF you want to download the unemployment rate data from FRED, then

    -   using a text editor, open `constants_system.r` (it is in the `r` folder of the project) - **(I recommend doing this with a text editor at this point, rather than opening it in RStudio, as that will trigger actions you might rather not have happen yet - nothing fatal, but you'll be waiting for those actions to end before you can proceed)**

    -   insert your FRED api key in the place noted in the file

# Project setup

-   start RStudio

-   open the project file `Pew_Revenue_Volatility.Rproj` in RStudio

-   wait for it to finish examining the packages the project uses

    -   when I did this to verify that I can transfer from one computer of mine to another it gave me numerous warnings about `DESCRIPTION` files missing; it appears to be a small non-damaging bug in the `renv` package and nothing to worry about

    -   I went ahead with the next step anyway and all worked

-   at the console, enter `renv::restore()`

    -   wait for it to finish installing packages; it will take a while

    -   this, too, gave me warnings, noting that `DESCRIPTION` files were missing for several packages; this, too, appears to be a non-damaging bug

-   assuming all good, proceed to "Check the setup"

# Check the setup

-   from within RStudio, open `libs_base.r`, which is in the `r` folder

    -   step through (execute) the `library(…)` statements one by one, making sure each library is installed and can load; when I did this on my transferee computer, there were no errors or warnings

    -   in addition to official CRAN packages, this step will install several packages that I created; they should install without trouble; if you want to verify how they were constructed, check the project directory `renv/local`, which has the source code for each package; also, they are [here](https://github.com/donboyd5)

        -   `bdata` - includes two data frames I created: `sgtax.a` (annual state government tax data from the U.S. Bureau of the Census) and `recessions` (official recession dates from the National Bureau of Economic Research)

            -   code that is in the data-raw directory of the `bdata` package (if you go to the source) downloads and gets the data; I would not recommend doing this; if you want to check the data, instead I would suggest spot-checking some numbers against the Census website; there are other ways to check, also; if you want thoughts on that, please let me know

        -   `bggtools` - selected functions and themes to use with the package `ggplot2`; simple stuff - I don't think you'll feel a need to do anything with this

        -   `bmaps` - has two data frames I created, with longitude/latitude for the U.S.: `states49`, which has long/lat for the 48 continental states and DC, and `states51`, with long/lat for the 50 states, with AK and HI as insets below the continental U.S., plus DC (I use `states51` in the project)

        -   `btools` - miscellaneous utility and statistical functions; nothing to do here; if you want to see a function, just type its name at the console --- e.g., typing "ht" will show you that `ht` is a function that displays the head and the tail of an object

        -   `BEAData` - includes the data frame `nipa`, which I created from data I downloaded from the BEA site; it has annual, quarterly, and monthly data from the National Income and Products Accounts (NIPA) from the U.S. Bureau of Economic Analysis; if you type `comment(nipa)` it will tell you the download date; I try to follow this convention for most data files in packages; the source code for the package downloads and parses BEA data

        -   `BLSdata` - monthly data from the U.S. Bureau of Labor Statistics; this project uses ...

        -   `qtax` - quarterly tax revenue data from the U.S. Bureau of the Census; has the data frame `qtax`, which has data I downloaded from the Census web site

-   repeat with `libs_ts.r`; these are packages for dealing with time-series data; I did not write any of them so it should be straightforward; they, too, should install without trouble

# Data preparation

1.  open `prep_data.r` (it is in the `r` project folder)

    -   the primary purposes of this program are to

        -   retrieve raw data

        -   clean it up

        -   and, in most cases, bundle files in a similar category into a single Rdata file (for example, several national economic data files are bundled into a national economy Rdata file); in a few cases, it also saves separate rds files

    -   you'll see my notes about how to navigate the code efficiently

    -   the program loads subprograms to accomplish major tasks; in general you'll want to open the sub programs and step through them line by line

    -   **there is one special sub program that I recommend you do not run: sub_ONETIME_downloads.r**

    -   This program downloads original source data and saves it in project directories. If you run this you will overwrite files that are in directories now. If the source agencies have changed those files, you may end up with data different than what I have used.

2.  `prep_vbase.r` prepares and saves the main state-tax-year data file, vbase

    -   best to run it line by line

    -   it loads some of the previously created files

    -   puts them into a common format

    -   "stacks" the separate data files into one long file

    -   creates inflation-adjusted versions of certain data

    -   constructs certain observation-specific (year-state-variable-real/nominal) transformations such as percent change from prior year, trend value, and percent deviation from trend

    -   construct volatility measures

3.  `prep_vol.r` prepares and saves files with summary volatility estimates by state, variable, and time period

    -   for example, the interquartile range of the percentage deviation from trend for selected variables, by decade

    -   step through the program line by line

# Analysis

-   open `Pew_Tax_Volatility.rmd`

-   step through the chunks one at a time

-   this will produce all of the figures, maps, and tables in the report

    -   It should produce figures (including map) and tables in approximately the order they appear in the report.

    -   The filenames for png and csv files will match those given in the endnote to each figure or table caption.

-   and will calculate and print certain facts that are inline in the report text
