---
title: "What can R do for _you_?"
author: "Davis Vaughan"
output:
  xaringan::moon_reader:
    css: ["default", "custom.css"]
    chakra: libs/remark-latest.min.js
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
```

class: dv

# Who am I?

???

- Thank you all for being here today

- Acutely aware that the word packages mean nothing to you right now

- tidyquant is my way of giving back to the R community to try and help make financial analysis in R a little bit easier.

- timekit provides some helper functions for time series analysis

- Probably the most important thing on this slide, I've spent alot of time trying to master the syntax of R, and finding resources to help me along the way. In my experience, you will run into things you don't understand, and for awhile you'll look like a deer caught in headlights, but one of the best things about R is the active community asking questions all across the internet, so your question has likely already been answered, and is probably just a google search away.

--

- Davis Vaughan

- Actuarial intern in ALM

- Master's student at UNC Charlotte

- Previously an intern at DataCamp

---
